### ISSUE TITLE
Wrapping the backend with PrintingProxy breaks the cache.

### ISSUE THREAD

**Issue by enfold-josh** [enfold/pas.plugins.ldap#2]
I get the following error after enabling the cache. If I comment out line [80](https://github.com/enfold/pas.plugins.ldap/blob/3a62821d2273d8387e777706495f653298878bb2/src/pas/plugins/ldap/cache.py#L80) in cache.py the error goes away.

------testpy3 2021-04-20 19:07:20,993 ERROR   [pas.plugins.ldap:101][waitress-0] Error in enumerateUsers
Traceback (most recent call last):
  File "/opt/plone/buildout/src/pas.plugins.ldap/src/pas/plugins/ldap/plugin.py", line 83, in _wrapper
    result = original_method(self, *args, **kwargs)
  File "/opt/plone/buildout/src/pas.plugins.ldap/src/pas/plugins/ldap/plugin.py", line 425, in enumerateUsers
    criteria=kw, attrlist=("login",), exact_match=exact_match
  File "/opt/plone/buildout-cache/eggs/node.ext.ldap-1.0b12-py3.6.egg/node/ext/ldap/ugm/_api.py", line 702, in search
    cookie=cookie
  File "/opt/plone/buildout-cache/eggs/node.ext.ldap-1.0b12-py3.6.egg/node/ext/ldap/ugm/_api.py", line 664, in raw_search
    cookie=cookie
  File "/opt/plone/buildout-cache/eggs/node-0.9.25-py3.6.egg/node/utils.py", line 250, in wrapped
    f_result = func(*args, **kws)
  File "/opt/plone/buildout-cache/eggs/node.ext.ldap-1.0b12-py3.6.egg/node/ext/ldap/_node.py", line 521, in search
    cookie=cookie
  File "/opt/plone/buildout-cache/eggs/node.ext.ldap-1.0b12-py3.6.egg/node/ext/ldap/session.py", line 59, in search
    cookie
  File "/opt/plone/buildout-cache/eggs/node.ext.ldap-1.0b12-py3.6.egg/node/ext/ldap/base.py", line 260, in search
    args
  File "/opt/plone/buildout/src/pas.plugins.ldap/src/pas/plugins/ldap/cache.py", line 89, in getData
    ret = self.get(key, force_reload=force_reload)
  File "/opt/plone/buildout/src/pas.plugins.ldap/src/pas/plugins/ldap/cache.py", line 100, in get
    res = self._client.get(key)
  File "/opt/plone/buildout-cache/eggs/dogpile.cache-1.1.2-py3.6.egg/dogpile/cache/region.py", line 765, in get
    value = self._get_from_backend(key)
  File "/opt/plone/buildout-cache/eggs/dogpile.cache-1.1.2-py3.6.egg/dogpile/cache/region.py", line 1265, in _get_from_backend
    self.backend.get_serialized(key)
  File "/opt/plone/buildout-cache/eggs/dogpile.cache-1.1.2-py3.6.egg/dogpile/cache/api.py", line 288, in get_serialized
    return cast(SerializedReturnType, self.get(key))
  File "/opt/plone/buildout/src/pas.plugins.ldap/src/pas/plugins/ldap/cache.py", line 35, in get
    value = self.proxied.get(key)
  File "/opt/plone/buildout-cache/eggs/dogpile.cache-1.1.2-py3.6.egg/dogpile/cache/api.py", line 245, in get
    raise NotImplementedError()
NotImplementedError

**Comment by dataflake** [comment]
I haven't seen that error before, please provide me with the exact buildout configuration so I am testing the same thing.

**Comment by dataflake** [comment]
I think I see what the problem is: In my sandbox I am explicitly pinning `dogpile.cache` to `< 1` so that overall the Python 2 compatibility is retained and the difference between the released version and your fork remains small.

If this is no concern I can drop that pin and test that, but I would also change all packaging data to drop the Python 2 compatibility claims.

Let me know what you prefer: Stick close to the released package and pin `dogpile.cache` or remove Python 2 compatibility in the fork. The risk then is making it harder and harder to port changes between the fork and the released package, you may end up with a version of `pas.plugins.ldap` that you have to maintain yourself for all eternity.

**Comment by dataflake** [comment]
FYI, I have merged all local buildout changes into the branch (see https://github.com/enfold/pas.plugins.ldap/commit/e312536382fc8f966a29f420007d66b6b3f7510f) and went through the whole process from `git clone` through using the cache in a Plone site and don't get errors.

Just so we're on the same page, this is how I create my virtual environments after the `git clone`:

```
git clone https://github.com/enfold/pas.plugins.ldap.git
cd pas.plugins.ldap
python3.6 -m venv .
bin/pip install -U pip wheel "setuptools<52" zc.buildout
```

Note the pin on `setuptools`, it's necessary for compatibility with `zc.buildout < 3` and also prevents one of those setuptools upgrade loops when running the buildout. After setting up the sandbox I used the Plone 5.2 buildout configuration:

```
bin/buildout -c buildout-5.2.x.cfg
```

**Comment by enfold-josh** [comment]
@dataflake While downgrading dogpile.cache does fix the problem, I do not want to be stuck on an old version of dogpile.cache for the sake of maintaining python2 compatibility. Please get it working with the latest dogpile.cache and drop python2 compatibility.

**Comment by dataflake** [comment]
Python 2 compatibility is now dropped and the latest versions of `dogpile.cache` and a few other dependencies are used.

**Comment by enfold-josh** [comment]
@dataflake Thank you. Looks good.
